In [1]:
import numpy as np
import matplotlib.pyplot as plt

##### Array

In [ ]:
a = np.array([1,2,3])
print(a)
print('\n')
b = np.array([[1, 2, 3], [2, 3, 4]])
print(b)
print('\n')
c = np.array([[1, 2], [2, 3], [3, 4]])
print(c)
## 2차원 만들고 쌓아감
d = np.array([[[1,2], [2, 3], [3, 4]], [[2, 3], [3, 4], [4, 5]]])
print('\n')
print(d)

[1 2 3]


[[1 2 3]
 [2 3 4]]


[[1 2]
 [2 3]
 [3 4]]


[[[1 2]
  [2 3]
  [3 4]]

 [[2 3]
  [3 4]
  [4 5]]]


In [29]:
print(a.shape)
print('\n')
print(b.shape)
print('\n')
print(c.shape)
print('\n')
print(d.shape)

(3,)


(2, 3)


(3, 2)


(2, 3, 2)


In [32]:
v = np.arange(36).reshape(3,4,3)
print(v)
print('\n')
print(v.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


(3, 4, 3)


In [37]:
print(np.sum(v, axis=0).shape)
print(np.sum(v, axis=0))
print('\n')
print(np.sum(v, axis=1).shape)
print(np.sum(v, axis=1))
print('\n')
print(np.sum(v, axis=2).shape)
print(np.sum(v,axis=2))
print('\n')

(4, 3)
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]


(3, 3)
[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]


(3, 4)
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]




In [38]:
ab = [1, 2, 3, 4, 5, 6, 7]
for i, number in enumerate(ab):
    print(i, number)

0 1
1 2
2 3
3 4
4 5
5 6
6 7


##### Stack vs Concatenate

In [44]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

In [47]:
c1 = np.concatenate((a, b), axis=0)
c2 = np.concatenate((a, b), axis=1)
print(c1)
print('\n')
print(c2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
## 차원 더해주기
s1 = np.stack((a, b), axis=0)
## 새로운 축이 중간에 생기는 것 // 행간 연결결
s2 = np.stack((a, b), axis=1)
## 새로운 축이 마지막에 생기는 것 // 위치끼리 생각
s3 = np.stack((a, b), axis=2)
print(s1)
print('\n')
print(s2)
print('\n')
print(s3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
